# Site settings
title: Seray Ibrahim
description: Seray Ibrahim
theme: minima
markdown: kramdown
baseurl: "" # Leave empty if repo name matches username.github.io
url: "https://seray-i.github.io"

# Specify which pages appear in header navigation
header_pages:
  - projects/index.md
  - publications/index.md
  - honours-service/index.md
