# Site settings
title: Seray Ibrahim
description: Seray Ibrahim
theme: minima
baseurl: "" # Leave empty if repo name matches username.github.io
url: "https://https://seray-i.github.io"

# Navigation links
nav:
  - home: /index.md
  - projects: /projects/
  - publications: /publications/
  - honours + service: /honours-service/
