# Site settings
title: Seray Ibrahim
description: Seray Ibrahim
theme: minima

# Navigation links
nav:
  - Home: /
  - About: /about/
  - Projects: /projects/
  - Publications: /publications/
  - Academic Service / Awards: /academic-service-awards/
